#!/usr/bin/env python
# coding: utf-8

import os
import streamlit as st


# ===============================
# PAGE CONFIG
# ===============================
st.set_page_config(
    page_title="Logs & Stats",
    page_icon="⚙️",
    layout="wide"
)

# ===============================
# BLUE THEME
# ===============================
st.markdown(
    """
    <style>
        .main {
            background: linear-gradient(180deg, #0b1f3a 0%, #0e2a52 100%);
            color: #e6edf3;
        }

        h1, h2, h3 {
            color: #7fb0ff;
        }

        section[data-testid="stSidebar"] {
            background-color: #081a33;
        }

        .block {
            background-color: #0f2f5c;
            border-left: 5px solid #7fb0ff;
            padding: 1.2rem;
            border-radius: 14px;
            margin-bottom: 1.5rem;
        }

        .log-box {
            background-color: #081a33;
            border: 1px solid #1c4a8c;
            border-left: 6px solid #7fb0ff;
            padding: 1rem;
            border-radius: 12px;
            font-family: monospace;
            white-space: pre-wrap;
            max-height: 520px;
            overflow-y: auto;
            color: #e6edf3;
        }

        .stat {
            background-color: #081a33;
            border-radius: 12px;
            padding: 1rem;
            text-align: center;
            border: 1px solid #1c4a8c;
        }

        .stat h2 {
            margin: 0;
            color: #7fb0ff;
        }

        .stat p {
            margin: 0;
            opacity: 0.85;
        }
    </style>
    """,
    unsafe_allow_html=True
)

# ===============================
# HEADER
# ===============================
st.sidebar.header("Logs & Monitoring")

st.header(
    "⚙️ AI Assistant — Logs & Statistics",
    divider="rainbow"
)

st.markdown(
    """
    This page displays system activity logs generated by the AI assistant.
    Logs include image uploads, detections, classifications,
    face recognition events, and emotion analysis.
    """
)

st.divider()


# ===============================
# LOAD LOGS
# ===============================
log_file = "history.log"
logs = ""

if os.path.exists(log_file):
    with open(log_file, "r", encoding="utf-8") as file:
        logs = file.read()


# ===============================
# STATS (SIMPLE BUT NICE)
# ===============================
st.markdown('<div class="block">', unsafe_allow_html=True)
st.subheader("📊 Quick statistics")

if logs.strip():
    lines = [l for l in logs.splitlines() if l.strip()]
    total_events = len(lines)
    last_event = lines[-1] if lines else "—"
else:
    total_events = 0
    last_event = "—"

col1, col2 = st.columns(2)

with col1:
    st.markdown(
        f"""
        <div class="stat">
            <h2>{total_events}</h2>
            <p>Total events logged</p>
        </div>
        """,
        unsafe_allow_html=True
    )

with col2:
    st.markdown(
        f"""
        <div class="stat">
            <h2>Last activity</h2>
            <p style="font-size:0.85rem">{last_event}</p>
        </div>
        """,
        unsafe_allow_html=True
    )

st.markdown('</div>', unsafe_allow_html=True)


# ===============================
# LOG VIEWER
# ===============================
st.markdown('<div class="block">', unsafe_allow_html=True)
st.subheader("🧾 Activity log")

if os.path.exists(log_file):
    if logs.strip():
        st.markdown(
            f"<div class='log-box'>{logs}</div>",
            unsafe_allow_html=True
        )
    else:
        st.info("Log file exists, but no activity has been recorded yet.")
else:
    st.warning(
        "No log file found. Interact with the application to generate logs."
    )

st.markdown('</div>', unsafe_allow_html=True)
